name: pingvin
channels:
  - ismrmrd
  - nvidia/label/cuda-12.3.0
  - conda-forge
  - defaults
dependencies:
  - anaconda-client=1.12.3                  # dev
  - armadillo=12.8.4                        # dev
  - boost=1.80.0
  - ccache=4.10.1                           # dev
  - breathe=4.34.0                          # dev
  - cmake=3.25.1                            # dev
  - cuda=12.3.0                             # cuda
  - cuda-runtime=12.3.0                     # cuda
  - eigen=3.4.0
  - fftw=3.3.9
  - fmt=8.1.1
  - gcc_linux-64=9.4.0                      # dev
  - gdb=11.1                                # dev
  - gmock=1.14.0                            # dev
  - gtest=1.14.0                            # dev
  - gxx_linux-64=9.4.0                      # dev
  - h5py=3.7.0
  - hdf5=1.10.6
  - howardhinnant_date=3.0.1                # dev
  - imagemagick=7.0.11_13                   # dev
  - ismrmrd=1.14.2
  - ismrmrd-python=1.14.0
  - junitparser=3.1.2
  - just=1.31.0                             # dev
  - libblas=*=*mkl
  - libxml2=2.9.14                          # dev
  - matplotlib=3.8.4                        # dev
  - mkl>=2024.1.0
  - mkl-include>=2024.1.0                   # dev
  - mrd=2.1.1
  - mrd-python=2.1.1
  - ninja=1.12.1                            # dev
  - nlohmann_json=3.11.3                    # dev
  - numpy=1.26.4
  - onnxruntime=1.18.1
  - packaging=24.0                          # dev
  - pip=24.0                                # dev
  - pugixml=1.12.1
  - pytest=8.3.3
  - python=3.10
  - pyyaml=6.0.1
  - range-v3=0.12.0
  - ripgrep>=14.0.0                         # dev
  - scipy=1.13.1
  - shellcheck=0.10.0                       # dev
  - siemens_to_ismrmrd=1.2.13
  - sysroot_linux-64=2.12
  - valgrind=3.23.0                         # dev
  - xsdata=24.5
  - xtensor=0.24.2
  - yq=3.4.3                                # dev