{% set major = load_file_regex(load_file='CMakeLists.txt', regex_pattern='(?<=set\(PINGVIN_VERSION_MAJOR )([^\)]+)') %}
{% set minor = load_file_regex(load_file='CMakeLists.txt', regex_pattern='(?<=set\(PINGVIN_VERSION_MINOR )([^\)]+)') %}
{% set patch = load_file_regex(load_file='CMakeLists.txt', regex_pattern='(?<=set\(PINGVIN_VERSION_PATCH )([^\)]+)') %}

package:
  name: pingvin
  version: {{ major.group(1) }}.{{ minor.group(1) }}.{{ patch.group(1) }}

source:
  path: ../

build:
  detect_binary_files_with_prefix: False
  ignore_prefix_files: True

requirements:
  build:
    - cmake=3.25.1
    - gcc_linux-64=9.4.0
    - gxx_linux-64=9.4.0
    - ninja=1.12.1

  host:
    - armadillo=12.8.4
    - boost=1.80.0
    - cuda=12.3.0
    - fftw=3.3.9
    - gmock=1.14.0
    - gtest=1.14.0
    - h5py=3.7.0
    - hdf5=1.10.6
    - howardhinnant_date=3.0.1
    - imagemagick=7.0.11_13
    - ismrmrd=1.14.2
    - ismrmrd-python=1.14.0
    - just=1.31.0
    - libblas=*=*mkl
    - libxml2=2.9.14
    - mkl>=2024.1.0
    - mkl-include>=2024.1.0
    - nlohmann_json=3.11.3
    - numpy=1.26.4
    - pugixml=1.12.1
    - python=3.10
    - range-v3=0.12.0
    - sysroot_linux-64=2.12
    - xtensor=0.24.2

  run:
    - boost=1.80.0
    - cuda-runtime=12.3.0
    - fftw=3.3.9
    - libblas=*=*mkl
    - mkl>=2024.1.0
    - mrd-python=2.1.1
    - numpy=1.26.4
    - onnxruntime=1.18.1
    - python=3.10
    - scipy=1.13.1

test:
  source_files:
    - test/e2e
  requires:
    - pytest=8.3.3
    - pyyaml=6.0.1

about:
  home: https://github.com/gadgetron/pingvin
  license: MIT
  license_file: LICENSE
  summary: 'Streaming Image Reconstruction Framework'
  description: |
    Pingvin reconstruction engine with support libraries and example pipelines.
  dev_url: https://github.com/gadgetron/pingvin
  doc_url: https://github.com/gadgetron/pingvin
  doc_source_url: https://github.com/gadgetron/pingvin/blob/master/README.md
