name: Pingvin Build

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  CONDA_CACHE_NUMBER: 1

defaults:
  run:
    # See https://github.com/marketplace/actions/setup-miniconda#important
    shell: bash -el {0}

jobs:
  build-and-test:
    #runs-on: ["self-hosted", "1ES.Pool=biomedsigproc-github-NC6s_v3"]
    runs-on: ["self-hosted", "1ES.Pool=biomedsigproc-gadgetron-NC6s_v3"]
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Check GPU availability
        shell: bash
        run: nvidia-smi

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          # Do not specify environment file - see Cache step below
          activate-environment: gadgetron

      - name: Get Date
        id: get-date
        shell: bash
        run: echo "YEARMONTH=$(date -u +'%Y%m')" >> $GITHUB_ENV

      - name: Cache Conda Env
        id: cache-conda
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs
          key:
              conda-${{ runner.os }}-${{ runner.arch }}-${{
              hashFiles('environment.yml') }}-${{
              env.YEARMONTH }}-${{
              env.CONDA_CACHE_NUMBER }}

      - name: Update Environment
        run: conda env update -n gadgetron -f environment.yml
        if: steps.cache-conda.outputs.cache-hit != 'true'

      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3

      - name: Build
        run: |
          mkdir -p build
          cd build/
          cmake -G Ninja \
              -D CMAKE_BUILD_TYPE=Release \
              -D USE_CUDA=ON \
              -D USE_MKL=ON \
              -D BUILD_DOCUMENTATION=OFF \
              -D CMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
              ../

      - name: Unit Test
        run: |
          cd build/
          ./test_all

